### ISSUE TITLE
Any reason to exclude TrinityCoreDocker from Watchtower?

### ISSUE THREAD

**Issue by opicron** [fdrake76/TrinityCoreDocker#3]
Thank you for the TrinityCoreDocker project. I am now an happy wow’er once again :).

I use Watchtower to keep my docker images up to date. Is there any reason to exclude TrinityCoreDocker from auto updating?

I could see that an new TrinityCore needs an new database version or something, or an hotfix sql.

Are you planning to keep updates backwards compatible? Or am I missing something and is the point moot?

Again thanks for your contribution!

**Comment by fdrake76** [comment]
Hey!  The TrinityCore application itself updates pretty much every day (sometimes several times a day), but the commits are mostly configuration updates that fix bugs around NPCs, quests, etc.  This image basically builds around that bleeding edge change once it detects an update was made.  The TrinityCore app itself is built around backwards compatibility where they offer SQL patches that autodetect when you run the program, so in that sense the docker image is backwards compatible.

As to if you should use Watchtower, that might depend on how you use TC.  If you are hosting this to play with friends and want to be sure you're stable among all else, you might want to run a separate set of test containers that smoke tests the bleeding edge first (e.g. you manually update and verify you can log in).  If you just enjoy screwing around for nostalgic purposes, I'd assume Watchtower would be fine.  Just understand that it will update very often.

**Comment by opicron** [comment]
Ah thanks for the update-- much appreciated!
